apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batch-runner.fullname" . }}
  labels:
    {{- include "batch-runner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "batch-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "batch-runner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "batch-runner.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config.configMap.enabled }}
          volumeMounts:
            - name: config-volume
              mountPath: /app
              subPath: {{ .Values.config.configMap.key}}
              readOnly: true
          {{- end }}
      {{- if .Values.config.configMap.enabled }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.config.configMap.name}}
      {{- end }}